comments = [
    "Top dah! Kece abis! 🔥👌",
    "Keren banget, nih! 🤩👏",
    "Bikin gemes deh! 😄🙌",
    "Gokil parah! Mantul! 💯🔥",
    "Mood booster banget! 😄🚀",
    "Bikin baper, sumpah! 🥺💖",
    "Kreatifnya nggak ada duanya! 🎨👍",
    "Nggak bisa berhenti nonton! 🎬✨",
    "Ini baru menyentuh hati! 💓🌟",
    "Keren banget, sampe speechless! 🤯🔝",
    "Wah, gila keren!",
    "Astagaaa, kreatif banget!",
    "Videonya keren!",
    "Mantul abis, gaspol!",
    "Videonya juara jiwa!",
    "Ini dia level dewa!",
    "Serius, kagum banget!",
    "Bikin speechless, top markotop!",
    "Kamu hebat banget sih!",
    "ini videonya keren abis!",
    "Jago bikin video yah",
    "Videomu keren",
    "Keren nih",
    "Kreatif banget dah",
    "Videonya ok",
    "Kreatif banget nih! 🎉👏",
    "Gak bosen nonton ini. 👀💯",
    "Lagi-lagi sukses! 🔥🙌",
    "Mood booster! 🌟😄",
    "Aduh, lucu banget! 😂👍",
    "Ini baru keren! 🤩👊",
    "Gemes deh, cantiknya! 😍❤️",
    "Seru abis nih! 🎈🕺",
    "Lanjutkan terus! 💪🚀",
    "Gw suka banget nih! 🔥👍",
    "Mantap abis, bro/sis! 🤙🎉",
    "Kreatif parah! Top markotop! 🎨🔝",
    "Seru banget, sumpah! 🤩🙌",
    "Video lu juara! Gw kagum! 🏆✨",
    "Bikin senyuman dari awal sampe akhir! 😄💖",
    "Ngga ada duanya, deh! Keren! 💯🔥",
    "Gw jadi pengen nonton lagi-lagi! 🔄🎬",
    "Ini konten yang gw butuhin, mantul! 🙏🌟",
    "Terus bikin video seru kayak gini! 👏🚀",
    "Gw auto ketagihan! Keren! 🔥👌",
    "Gokil abis, bro/sis! 🤪👏",
    "Mood langsung on pas nonton ini! 😄🙌",
    "Gaspol banget! Kece dah! 💯🔥",
    "Bikin happy dari pagi sampe malem! 🤩🌟",
    "Emang jago bikin konten, deh! 🎥✨",
    "Senyum nggak bisa ilang pas nonton! 😁💖",
    "Nggak heran kalo jadi viral, bagus bener! 📈🚀",
    "Ini nih yang bikin hari makin asik! 🎉🌈",
    "Jempol terus, bro/sis! Makin sukses! 👍🎯",
    "Seru abis nih! Mantul! 🔥👌",
    "Gw langsung hooked, sih! Keren! 🤩👏",
    "Luar biasa bikin happy! 🤪🙌",
    "Ngga nyesel nonton, top markotop! 💯🔥",
    "Bikin mood makin oke, thanks! 😄🚀",
    "Bener-bener kreatif, deh! 🎨✨",
    "Sumpah, gw senyum terus nonton ini! 😁💖",
    "Jelas bakal viral, asik banget! 📈🌟",
    "Nggak kebayang deh hari gw tanpa video lu! 🎉🌈",
    "Sukses terus, bro/sis! Keren abis! 👍🎯",
    "Seru abis nih! Mantul! 🔥👌",
    "Gw langsung hooked, sih! Keren! 🤩👏",
    "Luar biasa bikin happy! 🤪🙌",
    "Ngga nyesel nonton, top markotop! 💯🔥",
    "Bikin mood makin oke, thanks! 😄🚀",
    "Bener-bener kreatif, deh! 🎨✨",
    "Sumpah, gw senyum terus nonton ini! 😁💖",
    "Jelas bakal viral, asik banget! 📈🌟",
    "Nggak kebayang deh hari gw tanpa video lu! 🎉🌈",
    "Sukses terus, bro/sis! Keren abis! 👍🎯",
    "Luar biasa, terus berkarya! 🔥👏",
    "Gw selalu suka lihat konten lu! 🤩🙌",
    "Kreativitas lu gak ada batas! 🎨🔝",
    "Terus berinovasi, ya! Inspiratif! 🚀💡",
    "Jadi penggemar setia lu, bro/sis! 🙆‍♂️💯",
    "Gw beneran terinspirasi, keep it up! 💪🌟",
    "Setiap video lu selalu bikin senyum! 😄✨",
    "Pantesan banyak yang ngefans sama lu! 👑👍",
    "Sukses terus, deh! Luas masa depan lu! 💥🎉",
    "Salut dengan dedikasi dan usaha lu! 👏🔥",
    "Keren banget, terus berkarya ya! 🔥👏",
    "Lu emang oke, bikin konten selalu asik! 🤩🙌",
    "Ide-idenya menarik terus, gw dukung! 🎨🔝",
    "Lu tuh inspiratif, jangan pernah berhenti! 🚀💡",
    "Gw suka semua konten lu, teruskan! 🌟💯",
    "Setiap video lu punya daya tarik sendiri! 👍✨",
    "Jangan lupa terus kasih konten keren! 💪🎉",
    "Gw selalu senang lihat hasil kerja keras lu! 😄🌈",
    "Beneran salut sama dedikasi lu! 👑🔥",
    "Sukses terus ya, bro/sis! Pasti bisa! 💥🎯",
    "Keren Banget",
    "Wow!",
    "Keren!",
    "Ngga nyesel nonton!",
    "Inspiratif",
    "Keren Pokoknya",
    "Mantap!",
    "Gak kebayang gimana caranya bikin ini",
    "Support Selalu ka",
    "Sukses selalu",
    "Saling Support ya ka",
    "Tips menarik",
    "Keren bang",
    "Mantap ini video",
    "Sukses terus bang",
    "Jangan Lupa mampir ya",
    "Yuk saling support",
    "Kontenya mantap",
    "Wow, keren banget",
    "Keren banget!",
    "Mantap!",
    "Terus berkarya!",
    "Sangat menginspirasi!",
    "Bakat banget!",
    "Luar biasa!",
    "Keep up the good work!",
    "Kamu hebat!",
    "Semangat terus!",
    "Konten yang luar biasa!",
    "Kamu bikin hariku!",
    "Sukses selalu!",
    "Terus maju!",
    "Bangga banget!",
    "Kamu bikin ini kelihatan gampang!",
    "Bener-bener kreatif!",
    "Penuh semangat!",
    "Keep shining!",
    "Ayo terus berkarya!",
    "Ini keren banget!",
    "Jempol banget!",
    "Great job!",
    "Kreatif banget!",
    "Terus semangat!",
    "Love this!",
    "Kualitas konten top!",
    "Jangan berhenti!",
    "Bener-bener inspiratif!",
    "Salut buat kamu!",
    "Kamu bakat besar!",
    "Terus bersinar!",
    "Lanjutkan!",
    "Proud of you!",
    "This is amazing!",
    "Wow, keren banget!",
    "Kamu bikin kita bangga!",
    "Penuh energi positif!",
    "Keep going!",
    "Kamu bener-bener berbakat!",
    "Inspiratif!",
    "Ini luar biasa!",
    "Kamu bikin hariku lebih baik!",
    "Great content!",
    "Ini seru banget!",
    "Awesome job!",
    "Teruslah berbagi!",
    "Kamu inspirasi banyak orang!",
    "Aku suka banget!",
    "Terima kasih atas kontennya!",
    "Hebat banget!",
    "Luar biasa kerja kerasnya!",
    "Kontennya bagus banget!",
    "Kamu bikin bangga!",
    "Keep pushing forward!",
    "Penuh kreativitas!",
    "Kerja bagus!",
    "Semangat selalu!",
    "Teruslah berkarya!",
    "Kamu berbakat!",
    "Sangat inspiratif!",
    "Kamu hebat banget!",
    "Ini keren!",
    "Teruskan usaha bagus ini!",
    "Kamu bikin hariku cerah!",
    "Semoga sukses terus!",
    "Tetap semangat!",
    "Keren maksimal!",
    "Ayo terus maju!",
    "Bangga sama kamu!",
    "Bener-bener bikin terkesan!",
    "Kontennya menakjubkan!",
    "Kamu berbakat luar biasa!",
    "Kamu bikin ini terlihat mudah!",
    "Ini konten berkualitas!",
    "Jangan pernah menyerah!",
    "Kreatif luar biasa!",
    "Hasil karya yang hebat!",
    "Teruskan yang bagus ini!",
    "Penuh inovasi!",
    "Ini mengagumkan!",
    "Kerja keras terbayar!",
    "Ini bikin semangat!",
    "Salut dengan kreativitasmu!",
    "Konten hebat!",
    "Tetaplah menginspirasi!",
    "Ini sangat memotivasi!",
    "Kamu benar-benar luar biasa!",
    "Lanjutkan usaha ini!",
    "Kamu bikin bangga!",
    "Teruslah berkembang!",
    "Konten yang mengesankan!",
    "Sangat berbakat!",
    "Hebat banget hasil karyamu!",
    "Kamu bikin ini terlihat mudah!",
    "Kualitas konten yang tinggi!",
    "Jangan berhenti berkarya!",
    "Kreativitasmu luar biasa!",
    "Hasil kerja yang mengesankan!",
    "Semangat dan terus maju!",
]
